name: "Publish"

on:
  pull_request:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    env:
      working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application
    #- name:  Restore the application to populate the obj folder
    #  run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
    #  env:
    #    Configuration: ${{ matrix.configuration }}
    #    RuntimeIdentifier: win-${{ matrix.targetplatform }}
      
    - name: "Build & test"
      run: |
        dotnet publish SRTPluginManager.sln /p:PublishProfile=x86
        echo "done!"
        
    - name: "Zipping Contents"
      env:
        working-directory: SRTPluginManager/bin/Release/net5.0-windows/publish/
      run: zip -j publish.zip SRTPluginManager.exe
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      env:
        working-directory: SRTPluginManager/bin/Release/net5.0-windows/publish/
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          publish.zip
