name: "Publish"

on:
  pull_request:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    env:
      working-directory: .

    steps:
      # ...
      - name: "Build & test"
        run: |
          dotnet publish SRTPluginManager.sln /p:PublishProfile=x86
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            SRTPluginManager/bin/Release/net5.0-windows/publish/SRTPluginManager.exe
            LICENSE.txt
