name: "Publish"

on:
  pull_request:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    env:
      working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: "Build & test"
      run: |
        dotnet publish SRTPluginManager.sln /p:PublishProfile=x86

    - name: Zip the publish files
      run: |
        Add-Type -assembly 'System.IO.Compression'
        Add-Type -assembly 'System.IO.Compression.FileSystem'
        [System.IO.Compression.ZipArchive]$zipFile = [System.IO.Compression.ZipFile]::Open('publish.zip', ([System.IO.Compression.ZipArchiveMode]::Create))
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zipFile, 'SRTPluginManager/bin/Release/net5.0-windows/publish/SRTPluginManager.exe', 'SRTPluginManager.exe')
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zipFile, 'LICENSE', 'LICENSE')
        $zipFile.Dispose()
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Publish release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          publish.zip
